from tkinter import *
root=Tk()
sc=StringVar()
screen=Entry(root,textvariable=sc,font="lucida 20 bold").pack(fill=X ,padx=8,pady=9)

def click(event):
    global sc
    c=event.widget.cget("text")
    if c=="=":
        try:
            result=eval(sc.get())
            sc.set(result)
        except Exception as e:
            sc.set("Error")
    elif c=="C":
        sc.set("")
    else:
        sc.set(sc.get()+c)
root.title("Calculator")
#root.wm_iconbitmap("download.jpg")
root.geometry("280x430")
root.minsize(280,430)
root.maxsize(280,430)
f1=Frame(root,bg="grey")
b=Button(f1,text="1",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="2",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="3",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="+",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f1.pack(fill=X)

f1=Frame(root,bg="grey")
b=Button(f1,text="4",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="5",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="6",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="-",font="lucida 35 bold",padx=7)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f1.pack(fill=X)

f1=Frame(root,bg="grey")
b=Button(f1,text="9",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="8",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="7",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="/",font="lucida 35 bold",padx=7)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f1.pack(fill=X)

f1=Frame(root,bg="grey")
b=Button(f1,text="=",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="0",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f1,text="C",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f1.pack(fill=X)
b=Button(f1,text="*",font="lucida 35 bold")
b.pack(side=LEFT)
b.bind("<Button-1>",click)

root.mainloop()